Disable instant apps feature and settings, with adding users at lock screen every boot
GrapheneOS-Archive/platform_frameworks_base-old pull request #320
Opened 2023-02-01 07:12 UTC by quh4gko8

Merge with https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/140 for completeness, that is, to hide the now no-op Settings that toggle the moved settings

2023-02-01 07:16 UTC, quh4gko8 commented on packages/SystemUI/src/com/android/systemui/statusbar/policy/UserSwitcherControllerOldImpl.java
> -                mAddUsersFromLockScreen.setValue(
This removal makes the `mAddUsersFromLockScreen` remain at default false value as defined above

2023-02-01 07:20 UTC, quh4gko8 commented on packages/SystemUI/src/com/android/systemui/statusbar/policy/UserSwitcherControllerOldImpl.java
> -                mAddUsersFromLockScreen.setValue(
https://cs.android.com/android/platform/superproject/+/android-13.0.0_r18:frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/UserSwitcherControllerOldImpl.java;l=155-156

2023-02-01 07:23 UTC, quh4gko8 commented on packages/SystemUI/src/com/android/systemui/statusbar/policy/UserSwitcherControllerOldImpl.java
> -                mAddUsersFromLockScreen.setValue(
This resolves https://github.com/GrapheneOS/os-issue-tracker/issues/1927

2023-02-01 09:35 UTC, muhomorr commented on services/core/java/com/android/server/pm/PackageManagerService.java
>          ContentObserver co = new ContentObserver(mHandler) {
I think removing this ContentObserver entirely and adding
```
                for (int userId : UserManagerService.getInstance().getUserIds()) {
                    mWebInstantAppsDisabled.put(userId, true);
                }
```
in its place would be a better solution.

2023-02-01 09:35 UTC, muhomorr commented on core/java/android/provider/Settings.java
> +                ENABLE_EPHEMERAL_FEATURE,
I think a better solution would be to remove definitions of all these keys.
It'll ensure that all places that read them are dealt with.

2023-02-01 16:35 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsState.java
> +                if (isSettingBlockedFromReadAndWrite(name, mKey)) {
This can be moved up to line 1144 (after `name` is set) to avoid wasting time obtaining other attributes.

2023-02-01 17:00 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsState.java
> +            if (isSettingBlockedFromReadAndWrite(name, getKey())) {
Which operation does this block?

2023-02-02 12:55 UTC, quh4gko8 commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsState.java
> +            if (isSettingBlockedFromReadAndWrite(name, getKey())) {
Moving checks on places where `mSettings.put()` is called

2023-02-02 18:49 UTC, quh4gko8 commented
for simplicity, it will be reset every boot as disabled instead

2023-02-03 12:54 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +            SettingsState secureSetting = mSettingsStates.get(secureKey);
`secureSettings` are already retrieved above

2023-02-03 12:56 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +                globalSetting.insertSettingLocked(Settings.Global.ADD_USERS_WHEN_LOCKED,
`globalSettings` would be a more consistent name

2023-02-03 14:07 UTC, quh4gko8 commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +                globalSetting.insertSettingLocked(Settings.Global.ADD_USERS_WHEN_LOCKED,
I'll just reassign `secureSettings`

2023-02-03 14:07 UTC, quh4gko8 commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +                globalSetting.insertSettingLocked(Settings.Global.ADD_USERS_WHEN_LOCKED,
to be able to use same consistent name

2023-02-03 14:08 UTC, quh4gko8 commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +            SettingsState secureSetting = mSettingsStates.get(secureKey);
okay, can use that instead

2023-06-30 14:11 UTC, muhomorr requested changes

2023-06-30 14:11 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
> +            SettingsProviderHooks.insertSettingsOnBoot(SettingsRegistry.this, userId);
This method is also called when user is added, correct? If so, the method name is misleading.

2023-06-30 14:11 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProviderHooks.java
> +        secureSettings.insertSettingLocked(Settings.Secure.INSTANT_APPS_ENABLED, "0" /* (disabled) value */,
This setting is ignored when `ENABLE_EPHEMERAL_FEATURE` is set to 0

2023-06-30 14:11 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProviderHooks.java
> +            globalSettings.insertSettingLocked(Settings.Global.ADD_USERS_WHEN_LOCKED, "0" /* (disabled) value */,
To avoid repeating the same argument values, add a wrapper method that takes SettingsState, key and value as parameters.

2023-06-30 14:11 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProviderHooks.java
> +            globalSettings.insertSettingLocked(Settings.Global.ENABLE_EPHEMERAL_FEATURE, "0" /* (disabled) value */,
Split this out into a separate commit

2023-07-02 09:36 UTC, muhomorr commented on packages/SettingsProvider/src/com/android/providers/settings/SettingsProviderHooks.java
> +        if (state == null || key == null || value == null) {
It's better to crash here than to fail silently when `null` is passed.
In general, it's better to add null checks only when `null` is an expected value.

2023-07-03 12:29 UTC, closed without merging

2023-07-03 12:33 UTC, quh4gko8 commented
superseded by https://github.com/GrapheneOS/platform_frameworks_base/pull/388